module.exports = [
    "M (Red giant) Star",
    "M (Red dwarf) Star", // C'est tellement mal rempli, on sait jamais
    "M (Red super giant) Star",

    // "S-type Star",
    // "MS-type Star",
    // "C Star",
    // "CN Star",
    // "CJ Star",
    "T Tauri Star",
    // "Herbig Ae/Be Star"



    // "M-type star",
    // "M0 V",
    // "M0 VA",
    // "M0 Vz",
    // "M1 V",
    // "M1 Va",
    // "M2 V",
    // "M2 VA",
    // "M2V",
    // "M2VA",
    // "M3 V",
    // "M3 Va",
    // "M3V",
    // "M4 V",
    // "M4 VA",
    // "M5 V",
    // "M5 Va",
    // "M5V",
    // "M6 V",
    // "M6 VA",
    // "M7 V",
    // "M7 VA",
    // "M8 IVb",
    // "M8 V",
    // "M8 VA",
    // "M8VA",
    // "M9 V",
    // "M9 VI",
    // "M9 VIq",
];
